add_subdirectory(level_tools)

add_executable(dgo_unpacker
        dgo_unpacker.cpp)
target_link_libraries(dgo_unpacker common)

add_executable(dgo_packer
        dgo_packer.cpp)
target_link_libraries(dgo_packer common)

add_executable(vag_unpacker
        vag_unpacker.cpp)
target_link_libraries(vag_unpacker common)

add_executable(vag_packer
        vag_packer.cpp)
target_link_libraries(vag_packer common)

add_executable(bank_unpacker
        bank_unpacker.cpp)
target_link_libraries(bank_unpacker common)

add_executable(bank_packer
        bank_packer.cpp)
target_link_libraries(bank_packer common)

add_executable(memory_dump_tool
        memory_dump_tool/main.cpp)
target_link_libraries(memory_dump_tool common decomp)

add_executable(type_searcher
        type_searcher/main.cpp)
target_link_libraries(type_searcher common decomp)

add_executable(formatter
        formatter/main.cpp)
target_link_libraries(formatter common tree-sitter)
